/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
  "integration": "project-Academia_Library_-2AAqtYJjMKvQA9yVDgCvETxaQgAWR8Zj",
  "version": "2020-11-20"
}

export default ebconfig;